# Generated by Django 5.1.7 on 2025-03-28 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_adress', models.EmailField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=255)),
                ('number_of_persons', models.IntegerField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=255)),
            ],
        ),
    ]
